In [2]:
import numpy as np

In [3]:
print(np.__version__)
np.show_config()

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']


In [4]:
z = np.zeros(10)
print (z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
z = np.full(10, 2.5)
print (z)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


In [6]:
#Документация о функции из командной строки
!python3 -c " import numpy; numpy.info(numpy.add) "

Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.


In [7]:
z = np.zeros(10)
z[4] = 1
print (z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
z = np.arange(10,51)
print (z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [9]:
z = np.arange(51)
z = z[::-1]
print (z)

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1  0]


In [10]:
z = np.arange(12).reshape(3,4)
print (z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [12]:
z = np.random.random((3,3,3))
print(z)
z1=np.eye(3)
print(z1)

[[[0.69886399 0.16205891 0.71835288]
  [0.32859176 0.52279083 0.73209068]
  [0.18655051 0.83163402 0.66839756]]

 [[0.48877697 0.65613919 0.30315054]
  [0.79457661 0.13388269 0.057974  ]
  [0.98510788 0.37528841 0.08309944]]

 [[0.00153948 0.79669621 0.00480928]
  [0.9764899  0.04970762 0.24549426]
  [0.78776613 0.12460415 0.38194057]]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
z = np.random.random((10,10))
Zmin, Zmax = z.min(), z.max()

print(z)
print(Zmin, Zmax)

[[0.23807221 0.69380264 0.32655409 0.29184708 0.63626872 0.44402021
  0.67779589 0.54712145 0.96789234 0.74750732]
 [0.07219448 0.47299031 0.12072909 0.99523696 0.65083382 0.72009132
  0.13527639 0.38580453 0.10059759 0.25823131]
 [0.99136953 0.98816932 0.68699973 0.88280484 0.08381432 0.75956879
  0.44260097 0.36639163 0.183812   0.43917175]
 [0.30480125 0.0501718  0.93872764 0.91043726 0.63716673 0.02438891
  0.52932716 0.57884431 0.82199519 0.35550849]
 [0.16365612 0.71263207 0.70065902 0.11980613 0.27636787 0.41200466
  0.04406373 0.81812767 0.10366381 0.29704641]
 [0.54643051 0.12610849 0.66810483 0.7137938  0.17659704 0.79002664
  0.86016767 0.10995066 0.77325994 0.06161607]
 [0.32902569 0.94741722 0.41837282 0.46167328 0.00202642 0.86006711
  0.84406536 0.78155602 0.36261089 0.24609895]
 [0.74412155 0.24510007 0.3376524  0.50756649 0.28855989 0.95289182
  0.48409553 0.14593131 0.87319136 0.9734362 ]
 [0.49569178 0.56343675 0.50789462 0.68997874 0.50474591 0.83826507
  0.87557364

In [14]:
z = np.ones((10,10))

z[1:-1,1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [15]:
z = np.diag(np.arange(1,5), k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [16]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [17]:
z = np.tile(np.array([[0,1], [1,0]]), (4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [18]:
z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [19]:
z = np.arange(11)
z[(3 < z) & (z <= 8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [20]:
z = np.zeros((5,5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [21]:
def generate() :
    for x in range(10):
        yield x
z = np.fromiter(generate(), dtype=float, count=-1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [22]:
z = np.linspace(0,1,12) [1:-1]
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [23]:
z = np.random.random(10)
z.sort()
print(z)

[0.02462633 0.07833618 0.21180327 0.42286627 0.66777285 0.80145208
 0.82092164 0.8717524  0.90778249 0.92004644]


In [24]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [25]:
# Exsirsise 30

z = np.random.random((10,2))
x,y = z[:,0], z[:,1]
R = np.hypot(x, y)
T = np.arctan2(y,x)
print(R)
print(T)

[0.52752834 0.87382245 0.9105733  0.96007845 1.02356746 0.90705757
 0.72815721 0.87138622 0.95171695 0.64111412]
[1.079268   1.41684242 1.50767075 0.0037247  0.9941295  0.71094994
 0.54635066 0.76776828 1.55954565 0.39616846]


In [26]:
z = np.random.random(10)
z[z.argmax()] = 0
print(z)

[0.5813675  0.32673656 0.         0.87039384 0.05678538 0.24030939
 0.45401453 0.28308687 0.6020444  0.76342847]


In [27]:
z = np.zeros((10,10), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0,1,10), 
                            np.linspace(0,1,10))
print(z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [30]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x,y)
print(np.linalg.det(c))

3638.1636371179666


In [31]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo (dtype).min)
    print(np.iinfo (dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo (dtype).min)
    print(np.finfo (dtype).max)
    print(np.finfo (dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [34]:
#np.set_printoptions(threshold=np.nan)
#z = np.zeros((25,25))
#print(z)

In [38]:
z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(z-v)).argmin()
print(z)
print(z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
71


In [40]:
z = np.zeros(10, [('position', [('x', float,1),
                               ('y', float, 1)]),
                 ('color', [('r', float, 1),
                           ('g', float, 1),
                           ('b', float, 1)])])
print(z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-40-64e414c92311>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  z = np.zeros(10, [('position', [('x', float,1),


In [42]:
import scipy.spatial

z = np.random.random((10,2))
d = scipy.spatial.distance.cdist(z,z)
print(d)

[[0.         0.65532846 0.52322367 0.37555429 0.83089728 0.58823185
  1.03854544 1.0744553  0.68557811 0.31850147]
 [0.65532846 0.         0.32458147 0.65625483 0.32367729 0.07650561
  0.5060811  0.57148657 0.80727505 0.83387493]
 [0.52322367 0.32458147 0.         0.70855134 0.64174973 0.3192351
  0.8305932  0.89503726 0.9534644  0.79983106]
 [0.37555429 0.65625483 0.70855134 0.         0.67041008 0.58025755
  0.84983083 0.86156504 0.31005499 0.24172277]
 [0.83089728 0.32367729 0.64174973 0.67041008 0.         0.32542753
  0.20986923 0.26008507 0.68624235 0.89998877]
 [0.58823185 0.07650561 0.3192351  0.58025755 0.32542753 0.
  0.52387436 0.58324562 0.74036049 0.75791267]
 [1.03854544 0.5060811  0.8305932  0.84983083 0.20986923 0.52387436
  0.         0.07636698 0.80629643 1.08674632]
 [1.0744553  0.57148657 0.89503726 0.86156504 0.26008507 0.58324562
  0.07636698 0.         0.78989196 1.10149062]
 [0.68557811 0.80727505 0.9534644  0.31005499 0.68624235 0.74036049
  0.80629643 0.789891

In [43]:
z = np.arange(10, dtype=np.int32)
z = z.astype(np.float32, copy=False)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [47]:
z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(z):
    print(index, value)
    
for index in np.ndindex(z.shape):
    print(index, z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [48]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.hypot(x,y)
sigma, mu = 1.0, 0.0
g = np.exp(-((d - mu) ** 2 / (2.0 * sigma ** 2)))
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0