In [2]:
import numpy as np

In [3]:
print(np.__version__)
np.show_config()

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']


In [4]:
z = np.zeros(10)
print (z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
z = np.full(10, 2.5)
print (z)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


In [6]:
#Документация о функции из командной строки
!python3 -c " import numpy; numpy.info(numpy.add) "

Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.


In [7]:
z = np.zeros(10)
z[4] = 1
print (z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
z = np.arange(10,51)
print (z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [9]:
z = np.arange(51)
z = z[::-1]
print (z)

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1  0]


In [10]:
z = np.arange(12).reshape(3,4)
print (z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [12]:
z = np.random.random((3,3,3))
print(z)
z1=np.eye(3)
print(z1)

[[[0.8363619  0.7385998  0.49939951]
  [0.81443692 0.20269772 0.27336827]
  [0.37860479 0.17316383 0.63508094]]

 [[0.75313608 0.13557814 0.69310088]
  [0.30203386 0.49748036 0.5994605 ]
  [0.62207485 0.17609144 0.68374842]]

 [[0.7875336  0.18189274 0.15091423]
  [0.53567453 0.70076151 0.19300288]
  [0.16728028 0.10957494 0.57143709]]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
z = np.random.random((10,10))
Zmin, Zmax = z.min(), z.max()

print(z)
print(Zmin, Zmax)

[[0.84179051 0.87306635 0.72614317 0.22081558 0.88733536 0.70233694
  0.99205213 0.20071941 0.62628641 0.57059744]
 [0.9906812  0.3028643  0.70524744 0.02432651 0.44707914 0.16013209
  0.11321321 0.27073183 0.79843902 0.09383689]
 [0.73550743 0.09721585 0.37765746 0.90807748 0.45916307 0.39132151
  0.32174017 0.62874092 0.04491404 0.73220375]
 [0.45024142 0.11739275 0.48240648 0.67162783 0.83629175 0.45135651
  0.55979392 0.77721704 0.84865592 0.95183282]
 [0.40387836 0.55523826 0.42938959 0.36283155 0.84058803 0.96015416
  0.88973725 0.91365281 0.19963541 0.48617986]
 [0.70714351 0.02469685 0.93701546 0.57689155 0.04305099 0.84067109
  0.1783373  0.7384632  0.33201406 0.70520295]
 [0.60568624 0.88883564 0.31582903 0.31085711 0.04721515 0.35024659
  0.43499675 0.05547882 0.20608494 0.35588414]
 [0.94963115 0.61490583 0.97156948 0.75325097 0.89834591 0.49584892
  0.07389153 0.28145916 0.66396838 0.4079289 ]
 [0.61521539 0.8802391  0.83754576 0.45576317 0.29794429 0.41771899
  0.4209685 

In [14]:
z = np.ones((10,10))

z[1:-1,1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [15]:
z = np.diag(np.arange(1,5), k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [16]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [17]:
z = np.tile(np.array([[0,1], [1,0]]), (4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [18]:
z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [19]:
z = np.arange(11)
z[(3 < z) & (z <= 8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [20]:
z = np.zeros((5,5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [21]:
def generate() :
    for x in range(10):
        yield x
z = np.fromiter(generate(), dtype=float, count=-1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [22]:
z = np.linspace(0,1,12) [1:-1]
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [23]:
z = np.random.random(10)
z.sort()
print(z)

[0.05246595 0.07173268 0.07215753 0.28156828 0.29593185 0.32453615
 0.44722789 0.75584104 0.88911171 0.99212733]


In [24]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [25]:
# Exsirsise 30

z = np.random.random((10,2))
x,y = z[:,0], z[:,1]
R = np.hypot(x, y)
T = np.arctan2(y,x)
print(R)
print(T)

[0.87572155 0.72004087 0.55240761 0.94651228 0.8091718  0.95720021
 1.08550251 0.67853603 0.38529998 0.62020836]
[0.41033231 0.31488894 0.88731677 0.57153958 0.6702875  0.49419881
 0.69657024 0.13805049 1.37363337 1.30382752]


In [26]:
z = np.random.random(10)
z[z.argmax()] = 0
print(z)

[0.80228475 0.06853046 0.85098261 0.39952648 0.82199823 0.63959516
 0.         0.08588047 0.38322663 0.36099503]


In [27]:
z = np.zeros((10,10), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0,1,10), 
                            np.linspace(0,1,10))
print(z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [28]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x,y)
print(np.linalg.det(c))

3638.1636371179666


In [29]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo (dtype).min)
    print(np.iinfo (dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo (dtype).min)
    print(np.finfo (dtype).max)
    print(np.finfo (dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [30]:
#np.set_printoptions(threshold=np.nan)
#z = np.zeros((25,25))
#print(z)

In [31]:
z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(z-v)).argmin()
print(z)
print(z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
64


In [32]:
z = np.zeros(10, [('position', [('x', float,1),
                               ('y', float, 1)]),
                 ('color', [('r', float, 1),
                           ('g', float, 1),
                           ('b', float, 1)])])
print(z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-32-64e414c92311>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  z = np.zeros(10, [('position', [('x', float,1),


In [33]:
import scipy.spatial

z = np.random.random((10,2))
d = scipy.spatial.distance.cdist(z,z)
print(d)

[[0.         0.30095422 0.34938607 0.85524894 0.27822976 0.61702211
  0.45968183 0.64784655 0.63933234 0.07611434]
 [0.30095422 0.         0.56857336 0.87622567 0.06408108 0.52603915
  0.70219841 0.66902798 0.83534747 0.23285946]
 [0.34938607 0.56857336 0.         0.61744726 0.5775981  0.55614073
  0.13839156 0.447292   0.29000213 0.41393484]
 [0.85524894 0.87622567 0.61744726 0.         0.92587683 0.3999002
  0.65943075 0.2115276  0.5176644  0.88056774]
 [0.27822976 0.06408108 0.5775981  0.92587683 0.         0.5850929
  0.70694574 0.71672183 0.85351781 0.20410339]
 [0.61702211 0.52603915 0.55614073 0.3999002  0.5850929  0.
  0.66943408 0.24693811 0.65339654 0.61042704]
 [0.45968183 0.70219841 0.13839156 0.65943075 0.70694574 0.66943408
  0.         0.52178218 0.21580027 0.53049106]
 [0.64784655 0.66902798 0.447292   0.2115276  0.71672183 0.24693811
  0.52178218 0.         0.44348045 0.67014331]
 [0.63933234 0.83534747 0.29000213 0.5176644  0.85351781 0.65339654
  0.21580027 0.4434804

In [34]:
z = np.arange(10, dtype=np.int32)
z = z.astype(np.float32, copy=False)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [35]:
z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(z):
    print(index, value)
    
for index in np.ndindex(z.shape):
    print(index, z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [36]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.hypot(x,y)
sigma, mu = 1.0, 0.0
g = np.exp(-((d - mu) ** 2 / (2.0 * sigma ** 2)))
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [41]:
n = 5
p = 3
z = np.zeros((n,n))
np.put(z, np.random.choice(range(n*n), p, replace=False), 1)
print (z)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


In [46]:
x = np.random.rand(5, 5)
y = x - x.mean(axis=1, keepdims=True)
print(x)
print(y)

[[0.96222745 0.11808983 0.88624088 0.929481   0.37544159]
 [0.23908297 0.87246053 0.02393593 0.29499986 0.15912486]
 [0.94741694 0.19592058 0.9607629  0.56768311 0.97088169]
 [0.19448317 0.80325818 0.38449258 0.8169251  0.11072162]
 [0.72472593 0.35373366 0.65729417 0.98971179 0.96910484]]
[[ 0.3079313  -0.53620632  0.23194473  0.27518485 -0.27885456]
 [-0.07883786  0.5545397  -0.2939849  -0.02292097 -0.15879597]
 [ 0.21888389 -0.53261246  0.23222986 -0.16084993  0.24234864]
 [-0.26749296  0.34128205 -0.07748355  0.35494897 -0.35125451]
 [-0.01418815 -0.38518042 -0.08161991  0.25079771  0.23019076]]


In [47]:
z = np.random.randint(0, 10, (3,3))
n = 1 # Нумерация с нуля
print(z)
print(z[z[:,n].argsort()])

[[7 4 9]
 [1 9 6]
 [9 0 4]]
[[9 0 4]
 [7 4 9]
 [1 9 6]]


In [63]:
# 46
z = np.random.randint(0, 3, (3,10))
print((~z.any(axis=0)).any())
z

False


array([[2, 1, 2, 2, 0, 1, 0, 1, 2, 2],
       [2, 0, 2, 1, 0, 2, 1, 1, 2, 2],
       [0, 0, 2, 1, 2, 0, 0, 2, 0, 0]])

In [65]:
z = np.ones(10)
i = np.random.randint(0,len(z), 20)
z += np.bincount(i, minlength=len(z))
z

array([4., 3., 4., 3., 3., 1., 3., 3., 4., 2.])

In [67]:
w, h = 16,16
i = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
f = i[...,0]*256*256 + i[...,1]*256 + i[...,2]
n= len(np.unique(f))
print(np.unique(i))

[0 1]


In [71]:
a = np.random.randint(0, 10, (3,4,3,4))
sum = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[59 58 72 43]
 [48 47 51 48]
 [51 50 60 61]]


In [75]:
z = np.array([1,2,3,4,5])
nz = 3
z0 = np.zeros(len(z) + (len(z)-1)*(nz))
z0[::nz+1] = z
print(z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [77]:
a = np.arange(25).reshape(5,5)
a[[0,1]] = a [[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [79]:
faces = np.random.randint(0,100,(10,3))
f = np.roll(faces.repeat(2,axis=1), -1, axis=1)
f = f.reshape(len(f)*3,2)
f = np.sort(f,axis=1)
g = f.view(dtype=[('p0', f.dtype), ('p1', f.dtype)])
g = np.unique(g)
print(g)

[( 3, 57) ( 3, 67) ( 4, 63) ( 4, 68) (12, 77) (12, 81) (14, 62) (14, 69)
 (18, 22) (18, 73) (20, 21) (20, 50) (21, 50) (22, 73) (32, 57) (32, 71)
 (48, 77) (48, 94) (50, 62) (50, 90) (57, 67) (57, 71) (62, 69) (62, 90)
 (63, 68) (76, 76) (76, 94) (77, 81) (77, 94)]


In [89]:
C = np.bincount([1,2,5,8])
A = np.repeat(np.arange(len(C)), C)
print(C)
print(A)

[0 1 1 0 0 1 0 0 1]
[1 2 5 8]


In [90]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

print(moving_average(np.arange(20), 3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [91]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [92]:
Z = np.random.randint(0,2,100)
np.logical_not(arr, out=arr)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(arr, out=arr)

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [93]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0] - p[...,0]) * T[:,0] + (P0[:,1] - p[...,1]) * T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U * T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[5.5648739  5.69699305 1.52176243 2.94977292 9.90170428 2.95654246
 8.9754266  3.31206204 2.94444836 6.08204721]


In [94]:
Z = np.random.randint(0,10, (10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P - Rs//2)
Z_stop  = (P + Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start, 0)).tolist()
Z_start = (np.maximum(Z_start, 0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[0 0 4 0 4 5 7 6 1 8]
 [4 1 4 9 8 4 6 2 9 3]
 [3 3 7 0 2 5 1 5 8 3]
 [1 9 9 0 2 2 0 9 3 3]
 [2 1 6 7 9 7 6 4 1 0]
 [4 3 6 8 2 3 7 4 1 4]
 [7 2 6 1 8 8 6 5 5 8]
 [7 9 4 2 7 4 8 5 3 4]
 [3 9 5 2 3 2 3 9 6 6]
 [0 6 0 2 0 7 6 2 0 6]]
[[0 0 0 0 0]
 [0 0 0 4 0]
 [0 4 1 4 9]
 [0 3 3 7 0]
 [0 1 9 9 0]]


<ipython-input-94-681583fcb3c9>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


In [99]:
Z = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(Z)
print(Z)
rank

[[0.42322227 0.04522222 0.28875914 0.96407183 0.95168381 0.88233499
  0.38082993 0.78362    0.18633628 0.6112973 ]
 [0.61775386 0.18804742 0.61304653 0.14317549 0.8851538  0.83209925
  0.08649268 0.94272032 0.17122723 0.60743384]
 [0.46692004 0.50112785 0.03857347 0.97879471 0.864568   0.50341313
  0.31001986 0.25500678 0.76806575 0.9712841 ]
 [0.92301446 0.57078073 0.94731264 0.7626794  0.23267539 0.39030664
  0.54745663 0.46910132 0.90712049 0.50635613]
 [0.529254   0.95357117 0.11924303 0.69117275 0.79661613 0.4145206
  0.99115277 0.37125733 0.92439851 0.27815634]
 [0.64584967 0.44449147 0.48908509 0.68484671 0.87080922 0.56703225
  0.89694755 0.14965828 0.99293773 0.45762203]
 [0.90277583 0.48762638 0.90651405 0.48746416 0.07583291 0.65102592
  0.42213619 0.18514988 0.05406692 0.53558445]
 [0.82175095 0.29076555 0.01116028 0.55201976 0.01647172 0.54888919
  0.13446171 0.17778645 0.14208575 0.8588094 ]
 [0.68582887 0.34494472 0.97317944 0.62105218 0.95180733 0.18034974
  0.20181664 

10

In [101]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[9 8 6 8 0 4 0 7 1 8 8 6 3 0 4 3 0 7 0 7 9 4 2 7 6 3 5 8 9 2 1 1 2 4 2 6 9
 8 2 9 2 6 5 6 5 6 0 6 9 1]
6


In [102]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0] - n)
j = 1 + (Z.shape[1] - n)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 2 1]
   [2 1 3]
   [1 3 4]]

  [[2 1 1]
   [1 3 2]
   [3 4 1]]

  [[1 1 2]
   [3 2 3]
   [4 1 1]]

  [[1 2 3]
   [2 3 0]
   [1 1 3]]

  [[2 3 3]
   [3 0 1]
   [1 3 4]]

  [[3 3 2]
   [0 1 4]
   [3 4 2]]

  [[3 2 4]
   [1 4 3]
   [4 2 3]]

  [[2 4 2]
   [4 3 0]
   [2 3 3]]]


 [[[2 1 3]
   [1 3 4]
   [1 3 0]]

  [[1 3 2]
   [3 4 1]
   [3 0 1]]

  [[3 2 3]
   [4 1 1]
   [0 1 2]]

  [[2 3 0]
   [1 1 3]
   [1 2 3]]

  [[3 0 1]
   [1 3 4]
   [2 3 0]]

  [[0 1 4]
   [3 4 2]
   [3 0 0]]

  [[1 4 3]
   [4 2 3]
   [0 0 2]]

  [[4 3 0]
   [2 3 3]
   [0 2 4]]]


 [[[1 3 4]
   [1 3 0]
   [2 1 1]]

  [[3 4 1]
   [3 0 1]
   [1 1 3]]

  [[4 1 1]
   [0 1 2]
   [1 3 1]]

  [[1 1 3]
   [1 2 3]
   [3 1 2]]

  [[1 3 4]
   [2 3 0]
   [1 2 4]]

  [[3 4 2]
   [3 0 0]
   [2 4 3]]

  [[4 2 3]
   [0 0 2]
   [4 3 4]]

  [[2 3 3]
   [0 2 4]
   [3 4 1]]]


 [[[1 3 0]
   [2 1 1]
   [1 0 4]]

  [[3 0 1]
   [1 1 3]
   [0 4 3]]

  [[0 1 2]
   [1 3 1]
   [4 3 4]]

  [[1 2 3]
   [3 1 2]
   [3 4 4]]

  [[2 3 0]
   

In [105]:
class Symetric(np.ndarray):
    def __setitem__(self, (i,j), value):
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

SyntaxError: invalid syntax (<ipython-input-105-d29a7ad1b9f7>, line 2)

In [108]:
p, n = 5, 10
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(M)
print(V)
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1

In [110]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
S

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

In [111]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N == 3) & (Z[1:-1,1:-1]==0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1,1:-1] == 1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100):
    print(Z)
    Z = iterate(Z)

[[1 1 0 ... 1 0 0]
 [1 1 0 ... 1 1 0]
 [0 0 1 ... 1 1 0]
 ...
 [1 0 0 ... 1 1 0]
 [1 1 1 ... 0 1 0]
 [0 1 1 ... 1 1 1]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [

In [113]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(Z)
print (Z[np.argpartition(-Z,n)[:n]])

[8429  772 4136 ...  902 3003 1644]
[9997 9998 9999 9996 9995]


In [114]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))


[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [115]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[1 3 4 6 7]


In [116]:
# 70
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[2 0 1]
 [2 2 1]
 [4 3 2]
 [1 3 1]
 [0 0 3]
 [0 1 1]
 [1 3 1]
 [2 0 3]
 [0 2 1]
 [2 1 0]]
[[2 0 1]
 [2 2 1]
 [4 3 2]
 [1 3 1]
 [0 0 3]
 [0 1 1]
 [1 3 1]
 [2 0 3]
 [0 2 1]
 [2 1 0]]


In [117]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [118]:
Z = np.random.randint(0, 2, (6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]]


In [120]:
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.array([0, 1, 2])
B = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j', A, B)    # np.outer(A, B)

ValueError: operand has more dimensions than subscripts given in einstein sum, but no '...' ellipsis provided to broadcast the extra dimensions.