In [1]:
import numpy as np

In [3]:
print(np.__version__)
np.show_config()

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']


In [4]:
z = np.zeros(10)
print (z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
z = np.full(10, 2.5)
print (z)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


In [ ]:
#Документация о функции из командной строки
!python3 -c " import numpy; numpy.info(numpy.add) "

In [10]:
z = np.zeros(10)
z[4] = 1
print (z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
z = np.arange(10,51)
print (z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [14]:
z = np.arange(51)
z = z[::-1]
print (z)

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1  0]


In [16]:
z = np.arange(12).reshape(3,4)
print (z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
